server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh # payment_route 路由的id,没有规定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_routh2 # payment_route 路由的id,没有规定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            #- After=2022-11-13T23:34:18.810+08:00[Asia/Shanghai] #从什么时间后可以用
            #- Cookie=username,zzyy
            #- Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Method=GET

eureka:
  instance:
    hostname: cloud_gateway_service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
